//! The `vyper::ast` module implements the traits needed to work with the JSON abstract syntax
//! tree generated by the Vyper compiler.

use serde_json::Value;

/// Use the [`Value`] type directly to represent nodes
/// of the Vyper AST in JSON.
pub type VyperAST = Value;
